version: 2.1

jobs:
  build_and_deploy:
    docker:
      - image: circleci/node:latest
    working_directory: ~/app
    environment:
      FIREBASE_TOKEN: YOUR_FIREBASE_TOKEN_HERE
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run:
          name: Deploy to Firebase Hosting
          command: |
            npm install -g firebase-tools
            firebase deploy --only hosting:testgame1 --token "$FIREBASE_TOKEN"

workflows:
  build_and_deploy:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only:
                - main
